# Generated by Django 4.0.6 on 2022-07-26 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_collection_options_alter_collection_tittle_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='featuer_product',
            new_name='feature_product',  
        ),
    ]
